// Wire response shapes from the Coati services; nullable database values stay nullable.
export type RouteConsolidations = { id: string; model: string; version: string; actor_id: number; source_routes: { id: number; model: string; description: string | null; upstream_base: string | null; created_at: string; priority: number; enabled: boolean; upstream_id: number; upstream_model: string; vision_model: string | null; }[]; public_route: { id: number; model: string; description: string | null; upstream_base: string | null; updated_at: string | null; created_at: string; enabled: boolean; upstream_id: number | null; upstream_model: string | null; vision_model: string | null; fallback_enabled: boolean; }; created_at: string; rolled_back_at: string | null; rolled_back_by: number | null; }[]
export type PublicRoutes = { updated_at: string | null; id: number; model: string; upstream_id: number | null; upstream_model: string | null; vision_model: string | null; description: string | null; upstream_base: string | null; fallback_enabled: boolean; enabled: boolean; created_at: string; }[]
export type Routes = { description: string | null; upstream_base: string | null; id: number; model: string; upstream_id: number; upstream_model: string; vision_model: string | null; priority: number; enabled: boolean; created_at: string; }[]
export type listRequestsGatewayRepositoryResult = { items: { id: string; key_id: number; model: string; protocol: string; status: string; reserved_tokens: number; input_tokens: number; output_tokens: number; usage_source: string; cache_read_tokens: number | null; cache_miss_tokens: number | null; cache_miss_source: string | null; cache_write_tokens: number | null; cache_write_5m_tokens: number | null; cache_write_1h_tokens: number | null; reasoning_tokens: number | null; upstream_protocol: string | null; raw_usage: Record<string, unknown> | null; execution: Record<string, string | number | null> | null; request_context: { session_id: string | null; session_source: string | null; client_request_id: string | null; step_index: number | null; retry_index: number | null; context_tokens_estimate: number; context_bytes: number; message_count: number; tool_count: number; image_count: number; tool_result_bytes: number; largest_message_bytes: number; } | null; error: string | null; http_status: number | null; duration_ms: number | null; first_byte_ms: number | null; expires_at: string; created_at: string; }[]; total: number; page: number; per_page: number; }
export type Overview = { timezone: string; requests?: number | undefined; active?: number | undefined; failed?: number | undefined; tokens?: number | undefined; }
export type ProfileList = { items: { context_window: number; max_output_tokens: number; source: string; created_at: string; updated_at: string; catalog_synced_at: string | null; id: number; note: string | null; enabled: boolean; model_name: string; context_window_override: number | null; max_output_tokens_override: number | null; catalog_context_window: number | null; catalog_max_output_tokens: number | null; catalog_source: string | null; }[]; total: number; page: number; per_page: number; }
export type syncModelProfileServiceResult = { status: string; matched_count: number; source: string; } | { status: string; message: string; matched_count: number; missing_models: string[]; }
export type candidatesModelProfileServiceResult = { items: string[]; }
export type Accounts = { supported_models: string[]; has_proxy: boolean; has_secret: boolean; api_key_masked: string; key_fingerprint: string | null; updated_at: string | null; last_used_at: string | null; last_checked_at: string | null; last_success_at: string | null; last_error_at: string | null; last_latency_ms: number | null; cooldown_active: boolean; api_key_hint: string | null; proxy_hint: string | null; request_timeout_seconds: number; extra_headers: Record<string, string>; note: string | null; scope: string; owner_user_id: number | null; model_prefix: string; priority: number; default_model: string; provider: string; probe_expires_at: string | null; last_probe_at: string | null; last_probe_status: string | null; last_probe_latency_ms: number | null; weight: number; concurrency_limit: number; health_status: string; consecutive_failures: number; cooldown_until: string | null; health_observed_at: string | null; last_error: string | null; id: number; name: string; protocol: string; base_url: string; enabled: boolean; created_at: string; }[]
export type ProbeResult = { verified: boolean; health_updated: boolean; latency_ms: number; models: string[]; model_discovery_supported: boolean; }
export type UserLimits = { quota_updated_at: string | null; owner_id: number; daily_limit: number | null; concurrency_limit: number; rpm_limit: number; } | { owner_id: number; daily_limit: null; concurrency_limit: number; rpm_limit: number; }
export type Keys = { quota_group: string; rotated_from_id: number | null; id: number; owner_id: number; note: string | null; revoked_at: string | null; last_used_at: string | null; name: string; kind: string; prefix: string; scopes: string[]; models: string[]; daily_limit: number; concurrency_limit: number; rpm_limit: number; revoked: boolean; expires_at: string | null; created_at: string; }[]
export type AccountDirectory = { items: { id: number; name: string; provider: string; upstream_protocol: string; base_url: string; api_key_masked: string; key_fingerprint: string | null; supported_models: string[]; default_model: string; model_prefix: string; extra_headers: Record<string, string>; proxy_enabled: boolean; proxy_hint: string; priority: number; weight: number; request_timeout_seconds: number; enabled: boolean; note: string | null; health_status: string; consecutive_failures: number; last_checked_at: string | null; last_success_at: string | null; last_error_at: string | null; last_error: string | null; last_latency_ms: number | null; cooldown_until: string | null; cooldown_active: boolean; last_used_at: string | null; scope: string; owner_user_id: number | null; created_at: string | null; updated_at: string | null; }[]; total: number; page: number; per_page: number; summary: { total: number; enabled: number; disabled: number; used: number; healthy: number; unhealthy: number; cooling: number; recovering: number; unknown: number; }; }
export type UsageList = { items: { user_id: number | null; username: string | null; pat_id: number; credential_id: number | null; credential_name: string | null; upstream_model: string | null; route_id: number | null; route_name: string | null; provider: string | null; error_summary: string; id: string; request_id: string; parent_request_id: unknown | null; session_id: string | null; client_request_id: string | null; step_index: number | null; retry_index: number | null; model: string; inbound_protocol: string; upstream_protocol: string | null; prompt_tokens: number; completion_tokens: number; total_tokens: number; context_tokens_estimate: number | null; context_bytes: number | null; message_count: number | null; tool_count: number | null; image_count: number | null; tool_result_bytes: number | null; largest_message_bytes: number | null; cache_read_tokens: number | null; cache_write_tokens: number | null; cache_miss_tokens: number | null; cache_miss_source: string | null; usage_source: string; latency_ms: number | null; status: string; http_status: number | null; attempt_count: number; fallback_used: boolean; pat_name: string | null; pat_token_type: string | null; request_purpose: { code: string | undefined; label: string | undefined; } | null; created_at: string; }[]; total: number; page: number; per_page: number; }
export type personalUsageAnalyticsResult = { users: never[]; daily_quota_per_user: null; quota: { daily_quota: number | null; quota_override: number | null; quota_source: string; used_today: number; remaining: number | null; usage_percent: number | null; exhausted: boolean; } | null; filter_options: { models: { value: unknown; label: unknown; }[]; pats: { value: unknown; label: string; }[]; }; timezone: string; summary: { cache_hit_rate: number | null; successful_requests: number; success_rate: number; }; trend: { bucket: string; }[]; models: { tokens: number; items: { share_percent: number; }[]; }; }
export type adminUsageAnalyticsResult = { users: Record<string, unknown>[]; upstreams: Record<string, unknown>[]; daily_quota_per_user: number | null; filter_options: { users: Record<string, unknown>[]; models: { value: unknown; label: unknown; }[]; }; timezone: string; summary: { cache_hit_rate: number | null; successful_requests: number; success_rate: number; }; trend: { bucket: string; }[]; models: { tokens: number; items: { share_percent: number; }[]; }; }
export type QuotaList = { items: { updated_at: string | null; effective_quota: number | null; quota_source: string; remaining: number | null; usage_percent: number | null; exhausted: boolean; user_id: number; username: string; daily_token_quota: number | null; used_today: number; }[]; total: number; page: number; per_page: number; default_daily_quota: number | null; }
export type CacheKeys = { id: number; name: string; prefix: string; }[]
export type CacheModels = { object: string; data: { context_window: number; max_output_tokens: number; id: string; object: string; owned_by: string; }[]; }
export type SearchSettings = { provider: string; has_api_key: boolean; has_proxy: boolean; proxy_hint: string | null; timeout_seconds: number; source: { [k: string]: string; }; configured: boolean; }
export type SearchTestResult = { ok: boolean; provider: string; result_count: number; sample: string[]; }

export type Account = Accounts[number] & { display_models?: string[] }
export type Key = Keys[number]
export type Profile = ProfileList['items'][number]
export type Query = Record<string, string | number | boolean | null | undefined>
export type HealthSummary = AccountDirectory['summary']
export type AccountList = { items: Account[]; summary: HealthSummary }
export interface UserLimitsForm { daily_limit: number | null; concurrency_limit: number; rpm_limit: number }
export interface CheckResult { ok?: boolean; verified: boolean; message?: string; models?: string[] }
export interface MutationResult { token?: string; health_probe?: CheckResult }

export type UsageRow = UsageList['items'][number]
export type RequestDetail = listRequestsGatewayRepositoryResult['items'][number] & { username?: string | null; pat_name?: string | null; upstream_protocol?: string | null }
export interface Attempt { id: number; upstream_id: number; status: number | null; duration_ms: number | null; error: string | null; execution: Record<string, string | number | null> | null }

export type RoutePreflight = { schema_version: number; read_only: boolean; items: { model: string; status: string; version: string; source_ids: number[]; candidates: { source_id: number; account_id: number; account_name: string | null; enabled: boolean; priority: number; upstream_model: string; vision_model: string | null; has_base_override: boolean; }[]; reasons: { code: string; message: string; }[]; additional_accounts: { id: number; name: string; priority: number; }[]; proposal: { model: string; upstream_id: number | null; upstream_model: string | null; vision_model: string | null; upstream_base: string | null; description: string | null; fallback_enabled: boolean; enabled: boolean; } | null; }[]; summary: { total: number; ready_for_review: number; manual_review: number; blocked: number; }; }

export type CacheDimension = 'read' | 'write' | 'miss' | 'write_5m' | 'write_1h'
export type AnalyticsSummary = Record<`cache_${CacheDimension}_tokens`, number | null> & Record<`cache_${CacheDimension}_reported_requests`, number> & {
  requests: number; tokens: number; errors: number; prompt_tokens: number; completion_tokens: number;
  avg_latency_ms: number; p95_latency_ms: number; active_users: number; active_models: number;
  reasoning_tokens: number | null; estimated_requests: number; cache_hit_rate: number | null;
  successful_requests: number; success_rate: number;
}
export interface Analytics {
  timezone: string; summary: AnalyticsSummary;
  trend: { bucket: string; requests: number; tokens: number; errors: number; avg_latency_ms: number }[];
  models: { tokens: number; items: { model: string | null; requests: number; tokens: number; prompt_tokens: number; completion_tokens: number; share_percent: number }[] };
  users: { user_id: number; username: string; requests: number; tokens: number; errors: number }[];
  upstreams?: { upstream_id: string | null; name: string; protocol: string; requests: number; errors: number; tokens: number; cache_read_tokens: number | null; cache_read_reported_requests: number; cache_hit_rate: number | null }[];
  daily_quota_per_user: number | null;
  quota?: { daily_quota: number | null; used_today: number; remaining: number | null; exhausted: boolean } | null;
  filter_options: { users?: { value: number; label: string }[]; models: { value: string; label: string }[]; pats?: { value: number; label: string }[] };
}
export interface RouteHealth { summary: { total: number; enabled: number; attention: number } }

export type CacheUsage = { request_id: string | null; input_tokens: number | null; output_tokens: number | null; usage_source: string | null; cache_read_tokens: number | null; cache_write_tokens: number | null; cache_miss_tokens: number | null; cache_miss_source: string | null; cache_observed_tokens: number | null; cache_status: string; hit_ratio: number | null; upstream_id: number | null; upstream_name: string | null; upstream_model: string | null; upstream_protocol: string | null; }
export type CacheSummary = { completed_rounds: number; attempted_rounds: number; account_consistent: boolean | null; cache_read_tokens: number | null; cache_write_tokens: number | null; cache_miss_tokens: number | null; cache_status: string; hit_ratio: number | null; total_latency_ms: number; warning: string | null; }
export type CacheRound = CacheUsage & { round: number; status: string; latency_ms: number; http_status: number | null; error_summary?: string | null }
export interface CacheRecord { id: number; user_id?: number; name: string; model: string; prompt: string; rounds: number; max_tokens: number; status: string; summary: Partial<CacheSummary>; results: CacheRound[]; error_summary: string | null; created_at: string }
export interface CacheForm { name: string; key_id: string | number; model: string; prompt: string; rounds: number; max_tokens: number }
