/**
 * ai_prompt_templates
 *
 * Generated by drizzle-kit pull, then cleaned up. `$default` / `createdAt()` / `updatedAt()` only apply at runtime and don't go into the DDL.
 */

import { boolean, index, json, pgTable, serial, text, varchar } from 'drizzle-orm/pg-core'
import { toIso } from '@/common/serialize'
import { createdAt, updatedAt } from '../columns'

export const ai_prompt_templates = pgTable('ai_prompt_templates', {
  id: serial().primaryKey().notNull(),
  name: varchar({ length: 120 }).notNull(),
  category: varchar({ length: 50 }).default('custom'),
  description: text(),
  content: text().notNull(),
  /** Variable definitions: JSON array, e.g. ["requirement", "target_users"] (app-side default: empty array) */
  variables: json().$default(() => []),
  /** Tags: comma-separated string, e.g. "product,requirements" */
  tags: varchar({ length: 500 }).default(''),
  is_active: boolean().default(true),
  created_at: createdAt(),
  updated_at: updatedAt(),
}, (table) => [
  index('ix_ai_prompt_templates_category').using('btree', table.category),
  index('ix_ai_prompt_templates_name').using('btree', table.name),
])

export type AiPromptTemplate = typeof ai_prompt_templates.$inferSelect

export function aiPromptTemplateToDict(template: AiPromptTemplate) {
  const tagList = template.tags
    ? template.tags
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean)
    : []
  return {
    id: template.id,
    name: template.name,
    category: template.category || 'custom',
    description: template.description,
    content: template.content,
    variables: Array.isArray(template.variables) ? template.variables : [],
    tags: tagList,
    is_active: template.is_active !== null ? template.is_active : true,
    created_at: toIso(template.created_at),
    updated_at: toIso(template.updated_at),
  }
}
