/**
 * demo_records — the component gallery's shared demo data: every page pattern (standard list, card list, tree list,
 * stats list, detail tabs, step form, dynamic form, kanban, gantt, advanced table) reads and writes this one table.
 * Generated by scripts/scaffold.ts (name=demo_record, domain=component_center); parent_id's foreign key, tags and
 * extra were added by hand.
 *
 * - Timestamp columns use createdAt()/updatedAt() (app-side default `timezone('utc', now())`); output always goes through toIso()
 * - numeric columns stay strings; date columns are 'YYYY-MM-DD' text
 * - parent_id: self-reference (tree list, tree drag). The foreign key has no ON DELETE action, so a row with children
 *   can't be deleted; the service answers that with a clear 400 first (see DemoRecordService.deleteItem)
 * - Two independent orders, so one view's drags never scramble the other: sort_order = sibling order in the tree,
 *   board_order = card order within a status column of the kanban
 * - cover: a file-center id (scaffold `image` type), registered with syncFileRefs on write
 * - tags: JSON array of strings (card list); extra: JSON object of dynamic-form values (dynamic form)
 * - After changing the table, run `pnpm db:generate --name <description>` + `pnpm db:migrate`
 */

import { boolean, date, foreignKey, index, integer, jsonb, numeric, pgTable, serial, text, varchar } from 'drizzle-orm/pg-core'
import { toIso } from '@/common/serialize'
import { createdAt, updatedAt } from '../columns'

export const demo_records = pgTable(
  'demo_records',
  {
    id: serial().primaryKey().notNull(),
    name: varchar({ length: 100 }).notNull(),
    code: varchar({ length: 50 }).notNull().unique(),
    category: varchar({ length: 50 }),
    status: varchar({ length: 50 }).notNull().default('todo'),
    owner: varchar({ length: 50 }),
    priority: integer().notNull().default(0),
    is_active: boolean().notNull().default(true),
    amount: numeric({ precision: 10, scale: 2 }),
    quantity: integer(),
    progress: integer().notNull().default(0),
    start_date: date({ mode: 'string' }),
    end_date: date({ mode: 'string' }),
    parent_id: integer(),
    sort_order: integer().notNull().default(0),
    board_order: integer().notNull().default(0),
    cover: varchar({ length: 36 }),
    description: text(),
    tags: jsonb().$type<string[]>().notNull().default([]),
    extra: jsonb().$type<Record<string, unknown>>().notNull().default({}),
    created_at: createdAt(),
    updated_at: updatedAt(),
  },
  (table) => [
    foreignKey({ columns: [table.parent_id], foreignColumns: [table.id], name: 'demo_records_parent_id_fk' }),
    index('demo_records_parent_id_idx').on(table.parent_id),
  ],
)

export type DemoRecord = typeof demo_records.$inferSelect
export type NewDemoRecord = typeof demo_records.$inferInsert

export function demoRecordToDict(item: DemoRecord) {
  return {
    id: item.id,
    name: item.name,
    code: item.code,
    category: item.category,
    status: item.status,
    owner: item.owner,
    priority: item.priority,
    is_active: item.is_active,
    amount: item.amount,
    quantity: item.quantity,
    progress: item.progress,
    start_date: item.start_date,
    end_date: item.end_date,
    parent_id: item.parent_id,
    sort_order: item.sort_order,
    board_order: item.board_order,
    cover: item.cover,
    description: item.description,
    tags: item.tags,
    extra: item.extra,
    created_at: toIso(item.created_at),
    updated_at: toIso(item.updated_at),
  }
}
