/**
 * kanban_boards / kanban_cards
 *
 * Generated by drizzle-kit pull, then cleaned up. Columns like color/sort_order have DB DEFAULTs in the existing DB (.default());
 * created_at/updated_at are app-side defaults via createdAt()/updatedAt() from ../columns.
 */

import { relations } from 'drizzle-orm'
import { boolean, date, foreignKey, integer, pgTable, serial, text, unique, varchar } from 'drizzle-orm/pg-core'
import { toIso } from '@/common/serialize'
import { createdAt, updatedAt } from '../columns'

export const kanban_boards = pgTable('kanban_boards', {
  id: serial().primaryKey().notNull(),
  title: varchar({ length: 100 }).notNull(),
  board_code: varchar({ length: 50 }).notNull(),
  color: varchar({ length: 20 }).default('#4080FF'),
  sort_order: integer().default(0),
  wip_limit: integer().default(0),
  is_active: boolean().default(true),
  created_at: createdAt(),
  updated_at: updatedAt(),
}, (table) => [
  unique('kanban_boards_board_code_key').on(table.board_code),
])

export const kanban_cards = pgTable('kanban_cards', {
  id: serial().primaryKey().notNull(),
  board_id: integer().notNull(),
  title: varchar({ length: 200 }).notNull(),
  card_code: varchar({ length: 80 }).notNull(),
  description: text(),
  priority: varchar({ length: 20 }).default('medium'),
  assignee: varchar({ length: 100 }),
  due_date: date({ mode: 'string' }),
  tags: varchar({ length: 200 }),
  sort_order: integer().default(0),
  is_active: boolean().default(true),
  created_at: createdAt(),
  updated_at: updatedAt(),
}, (table) => [
  foreignKey({
      columns: [table.board_id],
      foreignColumns: [kanban_boards.id],
      name: 'kanban_cards_board_id_fkey'
    }).onDelete('cascade'),
  unique('kanban_cards_card_code_key').on(table.card_code),
])

export const kanbanBoardsRelations = relations(kanban_boards, ({ many }) => ({
  cards: many(kanban_cards),
}))

export const kanbanCardsRelations = relations(kanban_cards, ({ one }) => ({
  board: one(kanban_boards, { fields: [kanban_cards.board_id], references: [kanban_boards.id] }),
}))

export type KanbanBoard = typeof kanban_boards.$inferSelect
export type KanbanCard = typeof kanban_cards.$inferSelect

/** Kanban card output */
export function kanbanCardToDict(card: KanbanCard) {
  return {
    id: card.id,
    board_id: card.board_id,
    title: card.title,
    card_code: card.card_code,
    description: card.description,
    priority: card.priority || 'medium',
    assignee: card.assignee,
    due_date: card.due_date || null,
    tags: card.tags || '',
    sort_order: card.sort_order ?? 0,
    is_active: card.is_active,
    created_at: toIso(card.created_at),
    updated_at: toIso(card.updated_at),
  }
}

/**
 * Kanban column output: cards are the column's cards sorted by sort_order
 * (cards_count is the column's card count, with the same filters as the card list); cards are omitted when includeCards=false.
 */
export function kanbanBoardToDict(board: KanbanBoard, cards: KanbanCard[], includeCards = true) {
  const d: Record<string, unknown> = {
    id: board.id,
    title: board.title,
    board_code: board.board_code,
    color: board.color || '#4080FF',
    sort_order: board.sort_order ?? 0,
    wip_limit: board.wip_limit ?? 0,
    is_active: board.is_active,
    cards_count: cards.length,
    created_at: toIso(board.created_at),
    updated_at: toIso(board.updated_at),
  }
  if (includeCards) d.cards = cards.map(kanbanCardToDict)
  return d
}
