/**
 * Storage driver contract. Object keys are generated by the file center (content-addressed, see objectKeyFor), never
 * taken from user input.
 */

import type { Readable } from 'node:stream'

export type StorageName = 'local' | 's3'

export interface DownloadOptions {
  /** Name offered to the browser */
  filename: string
  contentType: string
  /** Show in the browser (images) instead of downloading */
  inline: boolean
  /** Bucket recorded on the file row (s3), so changing the configured bucket doesn't strand older files */
  bucket?: string | null
}

/** How to serve an object: stream it from this process, or redirect the client */
export type Download = { kind: 'stream'; stream: Readable } | { kind: 'redirect'; url: string }

export interface StorageDriver {
  readonly name: StorageName
  /** Bucket the objects live in (null for local) */
  readonly bucket: string | null
  /** Store an object; overwriting an existing key with the same content is fine */
  put(key: string, data: Buffer, contentType: string): Promise<void>
  exists(key: string): Promise<boolean>
  /** Remove an object; a missing object is not an error. `bucket`: the one recorded on the file row (s3) */
  delete(key: string, bucket?: string | null): Promise<void>
  download(key: string, options: DownloadOptions): Promise<Download>
}

const KEY_RE = /^[0-9a-f]{2}\/[0-9a-f]{64}$/

/** Content-addressed key: identical uploads share one object */
export function objectKeyFor(sha256: string): string {
  return `${sha256.slice(0, 2)}/${sha256}`
}

export function assertObjectKey(key: string): void {
  if (!KEY_RE.test(key)) throw new Error(`invalid object key: ${key}`)
}

/** Content-Disposition with an ASCII fallback plus the UTF-8 name (RFC 6266 / 5987) */
export function contentDisposition(filename: string, inline: boolean): string {
  const ascii = filename.replace(/[^\x20-\x7e]/g, '_').replace(/["\\]/g, '_')
  const encoded = encodeURIComponent(filename).replace(/['()*]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`)
  return `${inline ? 'inline' : 'attachment'}; filename="${ascii}"; filename*=UTF-8''${encoded}`
}
