/**
 * Standard list page template (shadcn/ui stack, TSX, with import/export)
 *
 * Replacement notes:
 *   - <Resource> → PascalCase resource name (e.g. CustomerOrder); <resource> → snake_case (e.g. customer_order);
 *     <resources> → the URL segment (e.g. customer-orders, used in file names)
 *   - <module> → admin or component_center (same as the module the page lives in)
 *   - The page title / resource name placeholders (PageHeader title, ImportDialog targetLabel) → the Chinese page title /
 *     resource name (add their translations to ./locales/<lang>.json)
 *   - Fill in the real fields: EXPORT_FIELDS (keys match the backend EXPORT_FIELD_MAP), FormValues, EMPTY_VALUES /
 *     toFormValues, columns, form fields
 *   - Field type → form component (FormValues type): str / text → FormInput / FormTextarea (string),
 *     int → FormNumber (number | null), float → FormNumber (number | string | null: the API returns decimals as strings),
 *     bool → FormSwitch (boolean), date / datetime → FormDate / FormDateTime (string),
 *     enum / dict → FormSelect (the option values | null), file / image → FormFileUpload / FormImageUpload (string | null)
 *   - Table columns: bool/status → StatusBadge; dates → formatDate / formatDateTime; numbers get tabular-nums
 *
 * Types: Row is the record the API returns (ApiItem, see ./api.ts); FormValues is what the form holds and submits,
 * checked against the create / edit body; DataTableColumn<Row>[] types each render's value from its dataIndex.
 * No `any` and no casts: when a type doesn't fit, fix the OpenAPI doc or the page, not the call site.
 *
 * i18n: Chinese source text is the key. Strings passed to shared components are translated inside them; text written
 * in JSX, native attributes and interpolated strings go through t() / <Trans>.
 *
 * Reference implementation: apps/web/src/modules/admin/pages/users/index.tsx; pages generated by `pnpm scaffold` are instances of this template.
 * Design and conventions: docs/frontend-design-system.md
 */
import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { AnimatePresence, motion } from 'motion/react'
import { Trans, useTranslation } from 'react-i18next'
import { Download, Plus, Upload, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { formatDateTime } from '@/lib/format'
import { toast } from '@/lib/toast'
import {
  createItem,
  deleteItem,
  downloadTemplate,
  exportItems,
  getItems,
  importItems,
  updateItem,
  type <Resource> as Row,
  type <Resource>ExportBody,
  type <Resource>FileType,
} from '@/modules/<module>/api/<resource>'
import ConfirmAction from '@/shared/components/ConfirmAction'
import DataTable, { type DataTableColumn } from '@/shared/components/DataTable'
import ExportDialog, { type ExportFieldOption, type ExportParams } from '@/shared/components/data-transfer/ExportDialog'
import ImportDialog from '@/shared/components/data-transfer/ImportDialog'
import { FilterBar, FilterSelect, SearchInput } from '@/shared/components/Filters'
import { FormDialog } from '@/shared/components/FormDialog'
import { FormInput, FormSelect, FormTextarea } from '@/shared/components/FormFields'
import PageHeader from '@/shared/components/PageHeader'
import StatusBadge, { type StatusTone } from '@/shared/components/StatusBadge'
import { useCrudList } from '@/shared/hooks/useCrudList'
import { downloadBlobFile } from '@/shared/utils/file'

// Adjust to the real fields (keys match the backend EXPORT_FIELD_MAP and the export body's fields enum)
const EXPORT_FIELDS = [
  { label: 'ID', value: 'id' },
  { label: '名称', value: 'name' },
  { label: '状态', value: 'status' },
  { label: '备注', value: 'remark' },
  { label: '创建时间', value: 'created_at' },
] as const satisfies readonly ExportFieldOption[]
/** Export column names (the values the export body accepts) */
type ExportField = (typeof EXPORT_FIELDS)[number]['value']
const isExportField = (value: string): value is ExportField => EXPORT_FIELDS.some((o) => o.value === value)
const normalizeFileType = (raw: string): <Resource>FileType => (raw === 'csv' || raw === 'xlsx' ? raw : 'xlsx')

// Enum: shared by the filter and the form; tone determines the StatusBadge color
type Status = NonNullable<Row['status']>
const STATUS_OPTIONS: { label: string; value: Status; tone: StatusTone }[] = [
  { label: '启用', value: 'active', tone: 'success' },
  { label: '停用', value: 'inactive', tone: 'neutral' },
]
const statusOption = (value: string | null) => STATUS_OPTIONS.find((o) => o.value === value)

/** What the form holds and submits (the create / edit body) */
interface FormValues {
  name: string
  status: Status | null
  remark: string
}

const EMPTY_VALUES: FormValues = { name: '', status: 'active', remark: '' }

/** Edit: take only form fields (id / created_at are not sent back); convert dates to picker format with formatDate(v, '') */
const toFormValues = (record: Row): FormValues => ({
  name: record.name ?? '',
  status: record.status ?? 'active',
  remark: record.remark ?? '',
})

export default function <Resource>Page() {
  const { t } = useTranslation()
  // Row is inferred from getItems' response
  const list = useCrudList(
    (params) =>
      getItems(params).catch((err: unknown) => {
        toast.apiError(err, '加载失败')
        return { items: [], total: 0 }
      }),
    { defaultPerPage: 20 },
  )
  const { data, total, loading, page, perPage, filters, fetchData, handlePageChange } = list
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [selectedKeys, setSelectedKeys] = useState<number[]>([])
  const [editing, setEditing] = useState<Row | null>(null)
  const [formOpen, setFormOpen] = useState(false)
  const [exportOpen, setExportOpen] = useState(false)
  const [importOpen, setImportOpen] = useState(false)

  const form = useForm<FormValues>({ defaultValues: EMPTY_VALUES })

  useEffect(() => {
    fetchData()
    // eslint-disable-next-line react-hooks/exhaustive-deps -- fetch only once on mount
  }, [])

  // ── Create / Edit ───────────────────────────────────────────────────────────
  const openCreate = () => {
    setEditing(null)
    form.reset(EMPTY_VALUES)
    setFormOpen(true)
  }

  const openEdit = (record: Row) => {
    setEditing(record)
    form.reset(toFormValues(record))
    setFormOpen(true)
  }

  // On throw, FormDialog stays open; the backend {error} message is shown by toast.apiError
  const submit = async (values: FormValues) => {
    try {
      if (editing) {
        await updateItem(editing.id, values)
        toast.success('更新成功')
      } else {
        await createItem(values)
        toast.success('创建成功')
      }
      setFormOpen(false)
      fetchData()
    } catch (err) {
      toast.apiError(err, '操作失败')
      throw err
    }
  }

  // ── Delete ──────────────────────────────────────────────────────────────────
  const remove = async (record: Row) => {
    try {
      await deleteItem(record.id)
      toast.success('删除成功')
      setSelectedKeys((keys) => keys.filter((k) => k !== record.id))
      fetchData()
    } catch (err) {
      toast.apiError(err, '删除失败')
      throw err
    }
  }

  // ── Filters (add the filter to the backend's list query and the OpenAPI doc) ─────────────────────
  const runSearch = () => {
    setSelectedKeys([])
    list.handleSearch({ search: search.trim(), status })
  }
  const reset = () => {
    setSearch('')
    setStatus('')
    setSelectedKeys([])
    list.handleReset()
  }

  // ── Export: selection takes priority (ids); if the backend supports filtered export, add the filters to the payload ─────
  const handleExport = async ({ fields, fileType }: ExportParams) => {
    const type = normalizeFileType(fileType)
    const payload: <Resource>ExportBody = { fields: fields.filter(isExportField), file_type: type }
    if (selectedKeys.length) payload.ids = selectedKeys
    try {
      const blob = await exportItems(payload)
      downloadBlobFile(blob, `<resources>_export.${type}`)
      toast.success('导出成功')
      setExportOpen(false)
    } catch (err) {
      toast.apiError(err, '导出失败')
    }
  }

  // ── Table columns: render's value is typed from dataIndex ─────────────────────
  const columns: DataTableColumn<Row>[] = [
    { key: 'id', title: 'ID', dataIndex: 'id', width: 72, className: 'text-muted-foreground tabular-nums' },
    { key: 'name', title: '名称', dataIndex: 'name', render: (value) => <span className="font-medium">{value}</span> },
    {
      key: 'status',
      title: '状态',
      dataIndex: 'status',
      width: 100,
      render: (value) => (
        <StatusBadge tone={statusOption(value)?.tone ?? 'neutral'} dot>
          {statusOption(value)?.label ?? value ?? '-'}
        </StatusBadge>
      ),
    },
    // An ellipsis column takes only the width left over, so give it a floor
    { key: 'remark', title: '备注', dataIndex: 'remark', minWidth: 160, ellipsis: true },
    {
      key: 'created_at',
      title: '创建时间',
      dataIndex: 'created_at',
      width: 180,
      className: 'text-muted-foreground tabular-nums',
      render: (value) => formatDateTime(value),
    },
    {
      key: 'actions',
      pin: 'end',
      title: '',
      align: 'right',
      width: 132,
      render: (_, record) => (
        <div className="flex justify-end gap-0.5">
          <Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => openEdit(record)}>
            {t('编辑')}
          </Button>
          <ConfirmAction title="确认删除该记录？" description="删除后不可恢复。" confirmText="删除" onConfirm={() => remove(record)}>
            <Button variant="ghost" size="sm" className="text-danger hover:text-danger h-7 px-2">
              {t('删除')}
            </Button>
          </ConfirmAction>
        </div>
      ),
    },
  ]

  return (
    <div>
      {/* Page header: at most one variant="brand" primary action per page; the rest are outline / ghost */}
      <PageHeader
        title="<页面标题>"
        actions={
          <>
            <Button variant="outline" size="sm" onClick={() => setImportOpen(true)}>
              <Upload />
              {t('导入')}
            </Button>
            <Button variant="outline" size="sm" onClick={() => setExportOpen(true)}>
              <Download />
              {t('导出')}
            </Button>
            <Button size="sm" variant="brand" onClick={openCreate}>
              <Plus />
              {t('新建')}
            </Button>
          </>
        }
      />

      {/* Filter bar */}
      <FilterBar onSearch={runSearch} onReset={reset}>
        <SearchInput value={search} onChange={setSearch} onSubmit={runSearch} placeholder="搜索…" />
        {/* The backend reads ?status= in routes.ts and filters in repository.ts (TODOs in docs/templates/backend) */}
        <FilterSelect value={status} onChange={setStatus} options={STATUS_OPTIONS} placeholder="状态" allLabel="全部状态" />
      </FilterBar>

      {/* Selection banner */}
      <AnimatePresence>
        {selectedKeys.length > 0 ? (
          <motion.div
            initial={{ opacity: 0, y: -6, height: 0 }}
            animate={{ opacity: 1, y: 0, height: 'auto' }}
            exit={{ opacity: 0, y: -6, height: 0 }}
            className="overflow-hidden"
          >
            <div className="bg-brand-soft mb-3 flex items-center gap-3 rounded-lg px-3 py-2 text-[13px]">
              <span>
                <Trans
                  i18nKey="已勾选 <0>{{count}}</0> 条，导出时将优先导出勾选数据"
                  values={{ count: selectedKeys.length }}
                  components={[<span className="font-medium tabular-nums" />]}
                />
              </span>
              <Button variant="ghost" size="sm" className="ml-auto h-7" onClick={() => setSelectedKeys([])}>
                <X />
                {t('清空勾选')}
              </Button>
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>

      {/* Table: loading skeleton, empty state and pagination are provided by DataTable */}
      <DataTable
        columns={columns}
        data={data}
        loading={loading}
        selectable
        selectedKeys={selectedKeys}
        onSelectionChange={setSelectedKeys}
        pagination={{ page, perPage, total, onChange: handlePageChange }}
        emptyTitle="还没有记录"
        emptyAction={
          <Button size="sm" onClick={openCreate}>
            <Plus />
            {t('新建')}
          </Button>
        }
        filtered={Boolean(filters.search || filters.status)}
        onClearFilters={reset}
      />

      {/* Create / Edit (react-hook-form): name must be a FormValues field; write rules' messages following backend/product copy */}
      <FormDialog open={formOpen} onOpenChange={setFormOpen} title={editing ? '编辑' : '新建'} form={form} onSubmit={submit}>
        <FormInput control={form.control} name="name" label="名称" placeholder="请输入名称" rules={{ required: '请输入名称' }} />
        <FormSelect control={form.control} name="status" label="状态" options={STATUS_OPTIONS} />
        <FormTextarea control={form.control} name="remark" label="备注" placeholder="选填" />
      </FormDialog>

      <ExportDialog
        open={exportOpen}
        onOpenChange={setExportOpen}
        title="导出设置"
        ruleHint={
          selectedKeys.length
            ? t('已勾选 {{count}} 条，将优先导出勾选数据。', { count: selectedKeys.length })
            : '未勾选数据时导出全部数据。'
        }
        fieldOptions={EXPORT_FIELDS}
        onConfirm={handleExport}
      />

      <ImportDialog
        open={importOpen}
        onOpenChange={setImportOpen}
        title="导入数据"
        targetLabel="<资源名>"
        onDownloadTemplate={(fileType) =>
          downloadTemplate(normalizeFileType(fileType))
            .then((blob) => {
              downloadBlobFile(blob, `<resources>_import_template.${normalizeFileType(fileType)}`)
              toast.success('模板已下载')
            })
            .catch((err: unknown) => toast.apiError(err, '模板下载失败'))
        }
        onImport={(file) => importItems(file)}
        onImported={(res) => {
          toast.success(t('导入成功：新增 {{created}} 条，更新 {{updated}} 条', { created: res?.created || 0, updated: res?.updated || 0 }))
          fetchData()
        }}
        errorExportFileName="<resources>_import_errors.csv"
      />
    </div>
  )
}
