import {
  Activity,
  Server,
  Search,
  AppWindow,
  BarChart3,
  Bell,
  Blocks,
  Box,
  Braces,
  Calendar,
  ChartColumn,
  ChartGantt,
  CircleAlert,
  Code2,
  CreditCard,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  FormInput,
  GitBranch,
  Globe,
  Hexagon,
  Home,
  IdCard,
  Inbox,
  Kanban,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  ListTree,
  MapPin,
  MessageSquare,
  Monitor,
  Network,
  Newspaper,
  PenLine,
  PieChart,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  Table2,
  Terminal,
  Type,
  Upload,
  User,
  Users,
  Webhook,
  Workflow,
  type LucideIcon,
} from 'lucide-react'

/**
 * Menu icons: menus.icon stores a lucide icon name (e.g. Home, Users), resolved here to the component.
 * To offer another icon, import it above and add it to MENU_ICONS (named imports keep the bundle small);
 * unknown names fall back to List.
 */
export const MENU_ICONS = {
  Activity,
  Server,
  Search,
  AppWindow,
  BarChart3,
  Bell,
  Blocks,
  Box,
  Braces,
  Calendar,
  ChartColumn,
  ChartGantt,
  CircleAlert,
  Code2,
  CreditCard,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  FormInput,
  GitBranch,
  Globe,
  Hexagon,
  Home,
  IdCard,
  Inbox,
  Kanban,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  ListTree,
  MapPin,
  MessageSquare,
  Monitor,
  Network,
  Newspaper,
  PenLine,
  PieChart,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  Table2,
  Terminal,
  Type,
  Upload,
  User,
  Users,
  Webhook,
  Workflow,
}

const BY_CODE: Partial<Record<string, LucideIcon>> = {
  dashboard: Home,
  system: Settings,
}

/** The menu fields the icon is resolved from */
export interface MenuIconSource {
  icon?: string | null
  code?: string | null
}

// Preserve icon names already stored by Coati and customized menus.
const SEMI_TO_LUCIDE = {
  IconActivity: Activity,
  IconKey: KeyRound,
  IconServer: Server,
  IconSearch: Search,
  IconApps: AppWindow,
  IconArticle: Newspaper,
  IconBarChart: BarChart3,
  IconBell: Bell,
  IconBox: Box,
  IconBrackets: Braces,
  IconBranch: GitBranch,
  IconCalendar: Calendar,
  IconCode: Code2,
  IconComment: MessageSquare,
  IconCreditCard: CreditCard,
  IconDesktop: Monitor,
  IconEdit2: PenLine,
  IconFile: FileText,
  IconFont: Type,
  IconGlobe: Globe,
  IconGridSquare: LayoutGrid,
  IconHexagon: Hexagon,
  IconHistogram: BarChart3,
  IconHome: Home,
  IconIdCard: IdCard,
  IconKanban: Kanban,
  IconLayers: Layers,
  IconList: List,
  IconMapPin: MapPin,
  IconPieChartStroked: PieChart,
  IconSend: Send,
  IconSetting: Settings,
  IconStar: Star,
  IconTerminal: Terminal,
  IconUser: User,
}

const ICONS_BY_NAME: Partial<Record<string, LucideIcon>> = { ...SEMI_TO_LUCIDE, ...MENU_ICONS }

export function resolveMenuIcon(menu: MenuIconSource | null | undefined): LucideIcon {
  if (!menu) return List
  return ICONS_BY_NAME[menu.icon ?? ''] || BY_CODE[menu.code ?? ''] || List
}
