/**
 * DemoRecord repository layer (generated by scripts/scaffold.ts, extended by hand): plain database reads / writes, no
 * business logic
 */

import { and, asc, count, desc, eq, gte, ilike, inArray, isNull, lte, notInArray, or, sql, type SQL } from 'drizzle-orm'
import type { AnyPgColumn } from 'drizzle-orm/pg-core'
import { clearFileRefs, syncFileRefs } from '@/common/file-refs'
import type { Executor } from '@/db/client'
import { demo_records, type DemoRecord, type NewDemoRecord } from '@/db/schema'
import type { DemoRecordFilters, DemoRecordSort, SortField } from './schema'

const t = demo_records

const SORT_COLUMNS: Record<SortField, AnyPgColumn> = {
  id: t.id,
  name: t.name,
  code: t.code,
  status: t.status,
  priority: t.priority,
  amount: t.amount,
  quantity: t.quantity,
  progress: t.progress,
  start_date: t.start_date,
  end_date: t.end_date,
  sort_order: t.sort_order,
  board_order: t.board_order,
  created_at: t.created_at,
  updated_at: t.updated_at,
}

/** Tree order (siblings): sort_order, then id. The kanban's card order is board_order, read through the list's sort_field */
const TREE_ORDER = [asc(t.sort_order), asc(t.id)]

export class DemoRecordRepository {
  constructor(private readonly db: Executor) {}

  /** The list filters as one condition (undefined = no filter) */
  filterWhere(f: DemoRecordFilters): SQL | undefined {
    const like = `%${f.search}%`
    return and(
      f.search ? or(ilike(t.name, like), ilike(t.code, like)) : undefined,
      f.category ? eq(t.category, f.category) : undefined,
      f.status ? eq(t.status, f.status) : undefined,
      f.owner ? eq(t.owner, f.owner) : undefined,
      f.isActive !== null ? eq(t.is_active, f.isActive) : undefined,
      f.parentId === 'root' ? isNull(t.parent_id) : f.parentId !== null ? eq(t.parent_id, f.parentId) : undefined,
      f.startFrom ? gte(t.start_date, f.startFrom) : undefined,
      f.startTo ? lte(t.start_date, f.startTo) : undefined,
    )
  }

  async listPage(page: number, perPage: number, filters: DemoRecordFilters, sort: DemoRecordSort | null) {
    const where = this.filterWhere(filters)
    const order = sort
      ? [(sort.direction === 'asc' ? asc : desc)(SORT_COLUMNS[sort.field]), desc(t.id)]
      : [desc(t.id)]
    const [totalRow] = await this.db.select({ n: count() }).from(t).where(where)
    const items = await this.db
      .select()
      .from(t)
      .where(where)
      .orderBy(...order)
      .limit(perPage)
      .offset((page - 1) * perPage)
    return { total: totalRow?.n ?? 0, items }
  }

  /** Every row in tree order (the tree is built in the service) */
  async listAll(): Promise<DemoRecord[]> {
    return this.db.select().from(t).orderBy(...TREE_ORDER)
  }

  /** Ids of the rows matching `where` */
  async listIds(where: SQL | undefined): Promise<number[]> {
    return (await this.db.select({ id: t.id }).from(t).where(where)).map((r) => r.id)
  }

  /** id → parent_id of every row (cycle checks) */
  async parentMap(): Promise<Map<number, number | null>> {
    const rows = await this.db.select({ id: t.id, parent_id: t.parent_id }).from(t)
    return new Map(rows.map((r) => [r.id, r.parent_id]))
  }

  /** Count, sums and counts per status / category of the rows matching `where` */
  async stats(where: SQL | undefined) {
    const [totals] = await this.db
      .select({
        total: count(),
        amount: sql<string>`coalesce(sum(${t.amount}), 0)::numeric(14, 2)::text`,
        quantity: sql<number>`coalesce(sum(${t.quantity}), 0)::bigint`.mapWith(Number),
      })
      .from(t)
      .where(where)
    const byStatus = await this.db.select({ value: t.status, n: count() }).from(t).where(where).groupBy(t.status)
    const byCategory = await this.db.select({ value: t.category, n: count() }).from(t).where(where).groupBy(t.category)
    return { totals: totals!, byStatus, byCategory }
  }

  /** Export: all rows when ids is null; ordered by id descending */
  async listForExport(ids: number[] | null): Promise<DemoRecord[]> {
    return this.db
      .select()
      .from(t)
      .where(ids ? inArray(t.id, ids) : undefined)
      .orderBy(desc(t.id))
  }

  async getById(id: number): Promise<DemoRecord | null> {
    const [row] = await this.db.select().from(t).where(eq(t.id, id)).limit(1)
    return row ?? null
  }

  async getByIds(ids: number[]): Promise<DemoRecord[]> {
    if (ids.length === 0) return []
    return this.db.select().from(t).where(inArray(t.id, ids))
  }

  async countChildren(id: number): Promise<number> {
    const [row] = await this.db.select({ n: count() }).from(t).where(eq(t.parent_id, id))
    return row?.n ?? 0
  }

  /** Children of `ids` that are not in `ids` themselves */
  async countChildrenOutside(ids: number[]): Promise<number> {
    const [row] = await this.db
      .select({ n: count() })
      .from(t)
      .where(and(inArray(t.parent_id, ids), notInArray(t.id, ids)))
    return row?.n ?? 0
  }

  async insert(values: NewDemoRecord): Promise<DemoRecord> {
    const [row] = await this.db
      .insert(t)
      .values(values)
      .returning()
    // Uploaded files used by this row are registered so the file center doesn't clean them up
    await syncFileRefs(this.db, 'demo_records', row!.id, { cover: row!.cover })
    return row!
  }

  async update(id: number, values: Partial<NewDemoRecord>): Promise<DemoRecord | null> {
    const [row] = await this.db
      .update(t)
      .set(values)
      .where(eq(t.id, id))
      .returning()
    if (row) await syncFileRefs(this.db, 'demo_records', row.id, { cover: row.cover })
    return row ?? null
  }

  /** The same values on several rows (batch update; cover is never part of it, so file refs don't change) */
  async updateMany(ids: number[], values: Partial<NewDemoRecord>): Promise<DemoRecord[]> {
    return this.db.update(t).set(values).where(inArray(t.id, ids)).returning()
  }

  async delete(id: number): Promise<void> {
    await clearFileRefs(this.db, 'demo_records', id)
    await this.db.delete(t).where(eq(t.id, id))
  }

  /** One statement, so a parent and its children selected together pass the foreign key (checked at statement end) */
  async deleteMany(ids: number[]): Promise<void> {
    for (const id of ids) await clearFileRefs(this.db, 'demo_records', id)
    await this.db.delete(t).where(inArray(t.id, ids))
  }
}
