/**
 * DemoRecord routes (generated by scripts/scaffold.ts, extended by hand): the shared API of the gallery's page
 * patterns (Component gallery → Page patterns, menu code cc_patterns)
 *
 * Permission codes (DEMO_RECORD_VIEW_CODES / DEMO_RECORD_PERMS in ./schema): reads need the directory code
 * cc_patterns or any page code under it; writes need the directory's buttons cc_patterns_add / _edit / _delete /
 * _export / _import (import and its template). Batch update and reorder are edits; batch delete is a delete.
 * Routes with an id check permissions first (403), then load the record (404), so a caller without permission can't
 * tell whether an id exists. JSON bodies are declared with routeBody (common/validation.ts): the schema goes on the route
 * for the OpenAPI body check, and is parsed after the permission check.
 */

import type { FastifyInstance, FastifyRequest } from 'fastify'
import { hasAnyMenuPermission, hasMenuPermission, loginRequired } from '@/common/auth'
import { getUploadedFile, intParam, parseIntParam, queryString } from '@/common/http'
import { parsePagination } from '@/common/pagination'
import { sendTable } from '@/common/tabular'
import { isDate, parseYesNo, routeBody } from '@/common/validation'
import { declareEvents } from '@/common/webhooks'
import {
  batchDeleteBody,
  batchUpdateBody,
  DEMO_RECORD_PERMS as PERMS,
  DEMO_RECORD_VIEW_CODES,
  demoRecordBody,
  demoRecordExportBody,
  reorderItem,
  SORT_FIELDS,
  type DemoRecordFilters,
  type DemoRecordSort,
} from './schema'
import { DemoRecordService } from './service'

const BASE = '/api/admin/component-center/demo-records'

// Webhook events this module emits (offered on the webhooks page)
declareEvents({
  'demo_record.created': '示例数据已新增',
  'demo_record.updated': '示例数据已修改',
  'demo_record.deleted': '示例数据已删除',
})

/** List / tree / stats filters from the query string */
function readFilters(request: FastifyRequest): DemoRecordFilters {
  const str = (key: string) => queryString(request, key).trim()
  const parent = str('parent_id')
  const date = (key: string) => (isDate(str(key)) ? str(key) : null)
  return {
    search: str('search'),
    category: str('category'),
    status: str('status'),
    owner: str('owner'),
    isActive: parseYesNo(str('is_active')),
    parentId: parent === 'root' ? 'root' : /^\d{1,9}$/.test(parent) ? Number(parent) : null,
    startFrom: date('start_from'),
    startTo: date('start_to'),
  }
}

/** sort_field + sort_dir; an unknown field means the default order (id descending) */
function readSort(request: FastifyRequest): DemoRecordSort | null {
  const field = SORT_FIELDS.find((f) => f === queryString(request, 'sort_field').trim())
  if (!field) return null
  return { field, direction: queryString(request, 'sort_dir').trim().toLowerCase() === 'asc' ? 'asc' : 'desc' }
}

export async function registerDemoRecordRoutes(app: FastifyInstance): Promise<void> {
  const service = new DemoRecordService(app.db, app.events)
  const opts = { preHandler: loginRequired }
  const itemPath = `${BASE}/${intParam('item_id')}`
  const itemId = (params: unknown) => parseIntParam((params as { item_id: string }).item_id)

  app.get(BASE, opts, async (request, reply) => {
    if (!(await hasAnyMenuPermission(request, ...DEMO_RECORD_VIEW_CODES))) {
      return reply.status(403).send({ error: '无权限' })
    }
    const { page, per_page } = parsePagination(request.query as Record<string, unknown>)
    return service.listItems(page, per_page, readFilters(request), readSort(request))
  })

  app.get(`${BASE}/tree`, opts, async (request, reply) => {
    if (!(await hasAnyMenuPermission(request, ...DEMO_RECORD_VIEW_CODES))) {
      return reply.status(403).send({ error: '无权限' })
    }
    return service.getTree(readFilters(request))
  })

  app.get(`${BASE}/stats`, opts, async (request, reply) => {
    if (!(await hasAnyMenuPermission(request, ...DEMO_RECORD_VIEW_CODES))) {
      return reply.status(403).send({ error: '无权限' })
    }
    return service.getStats(readFilters(request))
  })

  const create = routeBody(demoRecordBody, 'create')
  app.post(BASE, { ...opts, ...create.route }, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.add))) {
      return reply.status(403).send({ error: '无权限新建' })
    }
    return reply.status(201).send(await service.createItem(create.parse(request)))
  })

  app.get(itemPath, opts, async (request, reply) => {
    if (!(await hasAnyMenuPermission(request, ...DEMO_RECORD_VIEW_CODES))) {
      return reply.status(403).send({ error: '无权限' })
    }
    const item = await service.getOr404(itemId(request.params))
    return service.getItem(item)
  })

  const update = routeBody(demoRecordBody, 'patch')
  app.put(itemPath, { ...opts, ...update.route }, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.edit))) {
      return reply.status(403).send({ error: '无权限编辑' })
    }
    const item = await service.getOr404(itemId(request.params))
    return service.updateItem(item, update.parse(request))
  })

  app.delete(itemPath, opts, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.delete))) {
      return reply.status(403).send({ error: '无权限删除' })
    }
    const item = await service.getOr404(itemId(request.params))
    return service.deleteItem(item)
  })

  const batchUpdate = routeBody(batchUpdateBody, 'create')
  app.post(`${BASE}/batch-update`, { ...opts, ...batchUpdate.route }, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.edit))) {
      return reply.status(403).send({ error: '无权限批量更新' })
    }
    return service.batchUpdate(batchUpdate.parse(request))
  })

  const batchDelete = routeBody(batchDeleteBody, 'create')
  app.post(`${BASE}/batch-delete`, { ...opts, ...batchDelete.route }, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.delete))) {
      return reply.status(403).send({ error: '无权限批量删除' })
    }
    return service.batchDelete(batchDelete.parse(request))
  })

  const reorder = routeBody(reorderItem, 'array', '参数格式错误，需要数组')
  app.put(`${BASE}/reorder`, { ...opts, ...reorder.route }, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.edit))) {
      return reply.status(403).send({ error: '无权限排序' })
    }
    return service.reorder(reorder.parse(request))
  })

  const exportRequest = routeBody(demoRecordExportBody, 'create')
  app.post(`${BASE}/export`, { ...opts, ...exportRequest.route }, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.export))) {
      return reply.status(403).send({ error: '无权限导出' })
    }
    return sendTable(reply, await service.exportItems(exportRequest.parse(request)))
  })

  app.get(`${BASE}/template`, opts, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.import))) {
      return reply.status(403).send({ error: '无权限' })
    }
    return sendTable(reply, await service.downloadTemplate(queryString(request, 'file_type', 'xlsx')))
  })

  app.post(`${BASE}/import`, opts, async (request, reply) => {
    if (!(await hasMenuPermission(request, PERMS.import))) {
      return reply.status(403).send({ error: '无权限导入' })
    }
    return service.importItems(await getUploadedFile(request))
  })
}
