/**
 * DemoRecord module schema layer (generated by scripts/scaffold.ts, extended by hand): request bodies, list filters,
 * import / export columns and the permission codes of the shared demo API
 *
 * The body is declared field by field (common/validation.ts): each field's type, and the spec's required / default
 * rules. Import rows go through the same declaration (rowToBody). Cross-field and cross-row checks (dates, parent
 * records, cycles) live in the service.
 */

import { z } from 'zod'
import { formatDateTime } from '@/common/serialize'
import { field, invalidMessage, parseYesNo, required } from '@/common/validation'
import type { DemoRecord } from '@/db/schema'

// ─── Permissions ───────────────────────────────────────────────────────────────

/**
 * Every page pattern under Component gallery → Page patterns (menu code cc_patterns) uses this one API, so its permissions belong
 * to the directory, not to a page: the buttons cc_patterns_add / _edit / _delete / _export / _import hang under the
 * directory, and any page of the directory may read. A role granted a single page stores only that page's code (the
 * role editor keeps half-checked parents out), so reads accept the directory code or any page code listed here.
 * Add a page's code here when a new page pattern is added under the directory.
 */
export const DEMO_RECORD_VIEW_CODES = [
  'cc_patterns',
  'cc_patterns_standard_list',
  'cc_patterns_card_list',
  'cc_patterns_tree_list',
  'cc_patterns_stats_list',
  'cc_patterns_detail',
  'cc_patterns_step_form',
  'cc_patterns_dynamic_form',
  'cc_patterns_kanban',
  'cc_patterns_gantt',
  'cc_patterns_advanced_table',
] as const

export const DEMO_RECORD_PERMS = {
  add: 'cc_patterns_add',
  edit: 'cc_patterns_edit',
  delete: 'cc_patterns_delete',
  export: 'cc_patterns_export',
  import: 'cc_patterns_import',
} as const

// ─── Options ───────────────────────────────────────────────────────────────────

/** Status: the kanban columns (left to right) and the gantt states */
export const STATUSES = ['todo', 'in_progress', 'done', 'archived'] as const
export const CATEGORIES = ['product', 'design', 'engineering', 'marketing', 'operations'] as const
export type DemoRecordStatus = (typeof STATUSES)[number]
export type DemoRecordCategory = (typeof CATEGORIES)[number]

/** Choices of the enum fields: the value is stored, the label is shown (and accepted on import) */
export const FIELD_OPTIONS: Record<string, { value: string; label: string }[]> = {
  category: [{ value: 'product', label: '产品' }, { value: 'design', label: '设计' }, { value: 'engineering', label: '研发' }, { value: 'marketing', label: '市场' }, { value: 'operations', label: '运营' }],
  status: [{ value: 'todo', label: '待办' }, { value: 'in_progress', label: '进行中' }, { value: 'done', label: '已完成' }, { value: 'archived', label: '已归档' }],
}

/** Label of an enum value (the value itself when it isn't one of the choices) */
export function optionLabel(field: string, value: string | null): string | null {
  return FIELD_OPTIONS[field]?.find((o) => o.value === value)?.label ?? value
}

// ─── Request bodies ────────────────────────────────────────────────────────────

/** Dynamic-form values: any JSON object; missing / null → {} */
const extraObject = (label: string) =>
  z
    .record(z.string(), z.unknown(), { error: invalidMessage(label) })
    .nullish()
    .transform((v) => v ?? {})

export const demoRecordBody = z.object({
  name: field.requiredText('名称', '名称不能为空'),
  code: field.requiredText('编码', '编码不能为空'),
  category: field.optionalChoice('分类', CATEGORIES),
  status: field.choice('状态', STATUSES, 'todo'),
  owner: field.text('负责人'),
  priority: field.int('优先级', 0),
  is_active: field.bool('是否启用', true),
  amount: field.decimal('金额'),
  quantity: field.optionalInt('数量'),
  progress: field.int('进度', 0, { min: 0, max: 100 }),
  start_date: field.date('开始日期'),
  end_date: field.date('结束日期'),
  parent_id: field.id('上级记录'),
  sort_order: field.int('排序', 0),
  board_order: field.int('看板顺序', 0),
  cover: field.fileId('封面'),
  description: field.text('描述'),
  tags: field.textList('标签'),
  extra: extraObject('扩展字段'),
})

export type DemoRecordInput = z.output<typeof demoRecordBody>

/** Most rows one batch / reorder request may touch */
export const MAX_BATCH = 500

/** The selected records of a batch action: at least one id */
const selectedIds = () => field.ids('记录').refine((ids) => ids.length > 0, { error: '请选择要操作的记录' })

/**
 * Batch update: the selected ids and the fields to set. A field left out is not changed (`.optional()` keeps it
 * absent); owner / category sent as null are cleared, while status / is_active / priority are NOT NULL columns and a
 * null there is also "not changed".
 */
export const batchUpdateBody = z.object({
  ids: selectedIds(),
  status: field.optionalChoice('状态', STATUSES).optional(),
  category: field.optionalChoice('分类', CATEGORIES).optional(),
  owner: field.text('负责人').optional(),
  is_active: field.optionalBool('是否启用').optional(),
  priority: field.optionalInt('优先级').optional(),
})

export const batchDeleteBody = z.object({ ids: selectedIds() })

/**
 * One entry of a reorder request: the record and only the values to change. The kanban sends board_order (card order
 * within a column) and, when a card moves to another column, status; the tree sends sort_order (sibling order) and,
 * when a node moves, parent_id (null = move to the root). board_order / sort_order / status left out or null are not
 * changed (NOT NULL columns); an entry that changes nothing is a 400 (see DemoRecordService.reorder).
 */
export const reorderItem = z.object({
  id: required(field.id('记录'), '记录不能为空'),
  board_order: field.optionalInt('看板顺序').optional(),
  sort_order: field.optionalInt('排序').optional(),
  status: field.optionalChoice('状态', STATUSES).optional(),
  parent_id: field.id('上级记录').optional(),
})

/** Export request: the rows (ids; none = every row), the columns (fields; none = every column), the file type */
export const demoRecordExportBody = z.object({
  ids: field.ids('导出记录'),
  fields: field.textList('导出字段'),
  file_type: field.text('文件类型'),
})

// ─── List filters and sorting (query strings) ─────────────────────────────────

/** Filters shared by the list, the tree, the stats and the tree's search */
export interface DemoRecordFilters {
  /** Name or code contains */
  search: string
  category: string
  status: string
  owner: string
  isActive: boolean | null
  /** 'root' = records without a parent, a number = children of that record, null = any */
  parentId: 'root' | number | null
  /** start_date on or after (YYYY-MM-DD) */
  startFrom: string | null
  /** start_date on or before (YYYY-MM-DD) */
  startTo: string | null
}

/** Columns the list can be sorted by (sort_field); anything else falls back to the default order (id descending) */
export const SORT_FIELDS = [
  'id',
  'name',
  'code',
  'status',
  'priority',
  'amount',
  'quantity',
  'progress',
  'start_date',
  'end_date',
  'sort_order',
  'board_order',
  'created_at',
  'updated_at',
] as const
export type SortField = (typeof SORT_FIELDS)[number]

export interface DemoRecordSort {
  field: SortField
  direction: 'asc' | 'desc'
}

// ─── Import / export ───────────────────────────────────────────────────────────

/**
 * Export columns: a header string (value taken from the toDict field of the same name), or [header, value function]
 * (when a conversion is needed: enum values shown as their labels, booleans as yes / no text, times as the caller's
 * wall time, tags joined with commas). `extra` (dynamic-form values) is not exported.
 */
export type ExportColumn = string | [header: string, value: (item: DemoRecord) => unknown]

export const EXPORT_FIELD_MAP: Record<string, ExportColumn> = {
  id: 'ID',
  name: '名称',
  code: '编码',
  category: ['分类', (item) => optionLabel('category', item.category)],
  status: ['状态', (item) => optionLabel('status', item.status)],
  owner: '负责人',
  priority: '优先级',
  is_active: ['是否启用', (item) => (item.is_active ? '是' : '否')],
  amount: '金额',
  quantity: '数量',
  progress: '进度',
  start_date: '开始日期',
  end_date: '结束日期',
  parent_id: '上级记录',
  sort_order: '排序',
  board_order: '看板顺序',
  cover: '封面',
  description: '描述',
  tags: ['标签', (item) => item.tags.join(',')],
  created_at: ['创建时间', (item) => formatDateTime(item.created_at)],
}

/** Chinese name of a field (the export header; falls back to the field name when there is no export column) */
export function fieldLabel(field: string): string {
  const column = EXPORT_FIELD_MAP[field]
  return Array.isArray(column) ? column[0] : (column ?? field)
}

/** Import header map (key = header, value = field name); the first column is required */
export const IMPORT_HEADER_MAP: Record<string, string> = {
  '名称': 'name',
  '编码': 'code',
  '分类': 'category',
  '状态': 'status',
  '负责人': 'owner',
  '优先级': 'priority',
  '是否启用': 'is_active',
  '金额': 'amount',
  '数量': 'quantity',
  '进度': 'progress',
  '开始日期': 'start_date',
  '结束日期': 'end_date',
  '上级记录': 'parent_id',
  '排序': 'sort_order',
  '看板顺序': 'board_order',
  '封面': 'cover',
  '描述': 'description',
  '标签': 'tags',
}

/** An integer cell becomes a number; anything else stays text, so the declaration reports it */
const intCell = (text: string) => (/^[+-]?\d+$/.test(text.trim()) ? Number(text.trim()) : text)

/**
 * An import row (text cells) → the request-body shape, checked by the same declaration: numbers and yes / no are
 * parsed, option labels become values, tags are split on commas (`,` `，` `、`)
 */
export function rowToBody(row: Record<string, string>): Record<string, unknown> {
  const body: Record<string, unknown> = { ...row }
  if (row.category !== undefined) body.category = FIELD_OPTIONS.category!.find((o) => o.label === row.category)?.value ?? row.category
  if (row.status !== undefined) body.status = FIELD_OPTIONS.status!.find((o) => o.label === row.status)?.value ?? row.status
  if (row.priority !== undefined) body.priority = intCell(row.priority)
  if (row.is_active !== undefined) body.is_active = parseYesNo(row.is_active) ?? row.is_active
  if (row.quantity !== undefined) body.quantity = intCell(row.quantity)
  if (row.progress !== undefined) body.progress = intCell(row.progress)
  if (row.parent_id !== undefined) body.parent_id = intCell(row.parent_id)
  if (row.sort_order !== undefined) body.sort_order = intCell(row.sort_order)
  if (row.board_order !== undefined) body.board_order = intCell(row.board_order)
  if (row.tags !== undefined) body.tags = row.tags.split(/[,，、]/)
  return body
}

export interface ErrorRow {
  line: number
  reason: string
  row: Record<string, string>
}

export function buildErrorRow(line: number, reason: string, row: Record<string, unknown>): ErrorRow {
  return {
    line,
    reason,
    row: Object.fromEntries(Object.entries(row ?? {}).map(([k, v]) => [k, v === null || v === undefined ? '' : String(v)])),
  }
}
