/**
 * DemoRecord service layer (generated by scripts/scaffold.ts, extended by hand): business logic; throws ServiceError
 * and never touches HTTP objects
 *
 * Rules beyond the field declarations:
 * - end_date can't be before start_date
 * - parent_id must name an existing record, and never the record itself or one of its descendants (no cycles) — on
 *   create / update / import and in reorder, where every move of the request is applied before the check
 * - a record with children can't be deleted (400); a batch delete may remove a parent together with all of its
 *   children, but not leave children behind
 */

import type { z } from 'zod'
import { ServiceError } from '@/common/errors'
import { notFound } from '@/common/http'
import { dbConstraintError, writeError } from '@/common/db-errors'
import { buildTable, normalizeTableFileType, readTableFile, TableFileError, type UploadedFile } from '@/common/tabular'
import { exportColumns, parseBody } from '@/common/validation'
import type { EventBus } from '@/common/webhooks'
import type { Db } from '@/db/client'
import { demoRecordToDict, type DemoRecord, type NewDemoRecord } from '@/db/schema'
import { DemoRecordRepository } from './repository'
import {
  buildErrorRow,
  CATEGORIES,
  demoRecordBody,
  EXPORT_FIELD_MAP,
  fieldLabel,
  IMPORT_HEADER_MAP,
  MAX_BATCH,
  rowToBody,
  STATUSES,
  type batchDeleteBody,
  type batchUpdateBody,
  type demoRecordExportBody,
  type DemoRecordFilters,
  type DemoRecordInput,
  type DemoRecordSort,
  type ErrorRow,
  type reorderItem,
} from './schema'

type DemoRecordDict = ReturnType<typeof demoRecordToDict>
/** A tree node: the record and its children in sort_order */
export type DemoRecordNode = DemoRecordDict & { children: DemoRecordNode[] }

/** Whether `parentId` is `id` itself or one of its descendants in `parentOf` (id → parent_id) */
function wouldCycle(parentOf: Map<number, number | null>, id: number, parentId: number | null): boolean {
  const seen = new Set<number>()
  for (let cur = parentId; cur !== null && cur !== undefined; cur = parentOf.get(cur) ?? null) {
    if (cur === id) return true
    // A cycle already stored (never written by this service) must not loop forever
    if (seen.has(cur)) return true
    seen.add(cur)
  }
  return false
}

function checkDates(start: string | null, end: string | null): void {
  if (start && end && end < start) throw new ServiceError('开始日期不能晚于结束日期', 400)
}

export class DemoRecordService {
  private readonly repo: DemoRecordRepository

  constructor(
    private readonly db: Db,
    /** Webhook events (demo_record.created / updated / deleted), emitted after the write committed */
    private readonly events?: Pick<EventBus, 'emit'>,
  ) {
    this.repo = new DemoRecordRepository(db)
  }

  private async inTx<T>(fn: (repo: DemoRecordRepository) => Promise<T>): Promise<T> {
    try {
      return await this.db.transaction((tx) => fn(new DemoRecordRepository(tx)))
    } catch (err) {
      // Business errors as they are; input the database rejects (unique conflicts, too long …) → 400; anything else → 500
      throw writeError(err)
    }
  }

  async listItems(page: number, perPage: number, filters: DemoRecordFilters, sort: DemoRecordSort | null) {
    const { total, items } = await this.repo.listPage(page, perPage, filters, sort)
    return { items: items.map(demoRecordToDict), total, page, per_page: perPage }
  }

  /**
   * The records as a tree (roots and children in sort_order, then id). With filters, the matching records are kept
   * together with their ancestors (so every match stays reachable); a matching record keeps only matching children.
   */
  async getTree(filters: DemoRecordFilters): Promise<DemoRecordNode[]> {
    const rows = await this.repo.listAll()
    const where = this.repo.filterWhere(filters)
    let keep: Set<number> | null = null
    if (where) {
      const parentOf = new Map(rows.map((r) => [r.id, r.parent_id]))
      keep = new Set<number>()
      for (const id of await this.repo.listIds(where)) {
        for (let cur: number | null = id; cur !== null && !keep.has(cur); cur = parentOf.get(cur) ?? null) keep.add(cur)
      }
    }
    const nodes = new Map<number, DemoRecordNode>()
    for (const row of rows) if (!keep || keep.has(row.id)) nodes.set(row.id, { ...demoRecordToDict(row), children: [] })
    const roots: DemoRecordNode[] = []
    for (const node of nodes.values()) {
      const parent = node.parent_id !== null ? nodes.get(node.parent_id) : undefined
      if (parent) parent.children.push(node)
      else roots.push(node)
    }
    return roots
  }

  /** Totals of the records matching the list filters; every status / category is listed, with 0 when it has none */
  async getStats(filters: DemoRecordFilters) {
    const { totals, byStatus, byCategory } = await this.repo.stats(this.repo.filterWhere(filters))
    const countOf = (rows: { value: string | null; n: number }[], value: string | null) => rows.find((r) => r.value === value)?.n ?? 0
    return {
      total: totals.total,
      amount_sum: totals.amount,
      quantity_sum: totals.quantity,
      by_status: STATUSES.map((status) => ({ status, count: countOf(byStatus, status) })),
      by_category: [
        ...CATEGORIES.map((category) => ({ category, count: countOf(byCategory, category) })),
        // Records without a category, and values not among the options (e.g. written by an older version)
        { category: null, count: byCategory.filter((r) => !(CATEGORIES as readonly (string | null)[]).includes(r.value)).reduce((n, r) => n + r.n, 0) },
      ],
    }
  }

  async getOr404(id: number): Promise<DemoRecord> {
    const item = await this.repo.getById(id)
    if (!item) throw notFound()
    return item
  }

  getItem(item: DemoRecord) {
    return demoRecordToDict(item)
  }

  /** The parent must exist and must not be the record itself or one of its descendants (id = null: a new record) */
  private async checkParent(repo: DemoRecordRepository, id: number | null, parentId: number | null): Promise<void> {
    if (parentId === null) return
    if (!(await repo.getById(parentId))) throw new ServiceError('上级记录不存在', 400)
    if (id !== null && wouldCycle(await repo.parentMap(), id, parentId)) throw new ServiceError('上级记录不能是自身或其下级记录', 400)
  }

  async createItem(values: DemoRecordInput) {
    checkDates(values.start_date, values.end_date)
    const created = await this.inTx(async (repo) => {
      await this.checkParent(repo, null, values.parent_id)
      return repo.insert(values)
    })
    const dict = demoRecordToDict(created)
    await this.events?.emit('demo_record.created', dict)
    return dict
  }

  async updateItem(item: DemoRecord, values: Partial<DemoRecordInput>) {
    if (Object.keys(values).length === 0) return demoRecordToDict(item)
    checkDates(values.start_date !== undefined ? values.start_date : item.start_date, values.end_date !== undefined ? values.end_date : item.end_date)
    const updated = await this.inTx(async (repo) => {
      if (values.parent_id !== undefined) await this.checkParent(repo, item.id, values.parent_id)
      return repo.update(item.id, values)
    })
    if (!updated) throw notFound()
    const dict = demoRecordToDict(updated)
    await this.events?.emit('demo_record.updated', dict)
    return dict
  }

  async deleteItem(item: DemoRecord) {
    await this.inTx(async (repo) => {
      if ((await repo.countChildren(item.id)) > 0) throw new ServiceError('存在下级记录，不能删除', 400)
      await repo.delete(item.id)
    })
    await this.events?.emit('demo_record.deleted', { id: item.id })
    return { message: '删除成功' }
  }

  /** The records of a batch request, all of which must exist */
  private async selected(repo: DemoRecordRepository, ids: number[]): Promise<DemoRecord[]> {
    if (ids.length > MAX_BATCH) throw new ServiceError(`一次最多处理 ${MAX_BATCH} 条记录`, 400)
    const rows = await repo.getByIds(ids)
    if (rows.length !== ids.length) throw new ServiceError('记录不存在或已删除', 400)
    return rows
  }

  /** Batch update: the fields present in the body are set on every selected record */
  async batchUpdate({ ids, ...patch }: z.output<typeof batchUpdateBody>) {
    // NOT NULL columns: null means "not changed", like a field left out
    const values: Partial<NewDemoRecord> = Object.fromEntries(
      Object.entries(patch).filter(([key, value]) => value !== undefined && !(value === null && ['status', 'is_active', 'priority'].includes(key))),
    )
    if (Object.keys(values).length === 0) throw new ServiceError('请至少修改一个字段', 400)
    const rows = await this.inTx(async (repo) => {
      await this.selected(repo, ids)
      return repo.updateMany(ids, values)
    })
    for (const row of rows) await this.events?.emit('demo_record.updated', demoRecordToDict(row))
    return { message: `已更新 ${rows.length} 条记录` }
  }

  /** Batch delete: a parent may go together with all of its children, but no child may be left behind */
  async batchDelete({ ids }: z.output<typeof batchDeleteBody>) {
    await this.inTx(async (repo) => {
      await this.selected(repo, ids)
      if ((await repo.countChildrenOutside(ids)) > 0) throw new ServiceError('所选记录包含未选中的下级记录，不能删除', 400)
      await repo.deleteMany(ids)
    })
    for (const id of ids) await this.events?.emit('demo_record.deleted', { id })
    return { message: `已删除 ${ids.length} 条记录` }
  }

  /**
   * Reorder (kanban drag, tree drag, manual order): each entry sets only the values it carries — board_order (card
   * order within a kanban column), sort_order (sibling order in the tree), status, parent — so a kanban drag never
   * touches the tree's order and vice versa. An entry carrying none of them is a 400. All moves are applied, then
   * checked together: parents must exist and no record may end up under itself. Only records whose values change are
   * written.
   */
  async reorder(items: z.output<typeof reorderItem>[]) {
    if (items.length === 0) return { message: '排序成功', updated: 0 }
    // null board_order / sort_order / status mean "not changed" (NOT NULL columns); parent_id null = move to the root
    const carriesChange = (i: z.output<typeof reorderItem>) =>
      typeof i.board_order === 'number' || typeof i.sort_order === 'number' || Boolean(i.status) || i.parent_id !== undefined
    if (!items.every(carriesChange)) throw new ServiceError('排序项至少要指定一个要调整的字段', 400)
    const ids = items.map((i) => i.id)
    if (new Set(ids).size !== ids.length) throw new ServiceError('排序列表中有重复的记录', 400)
    const changed = await this.inTx(async (repo) => {
      const current = new Map((await this.selected(repo, ids)).map((r) => [r.id, r]))
      const parentOf = await repo.parentMap()
      for (const item of items) if (item.parent_id !== undefined) parentOf.set(item.id, item.parent_id)
      for (const item of items) {
        if (item.parent_id === undefined || item.parent_id === null) continue
        if (!parentOf.has(item.parent_id)) throw new ServiceError('上级记录不存在', 400)
        if (wouldCycle(parentOf, item.id, item.parent_id)) throw new ServiceError('上级记录不能是自身或其下级记录', 400)
      }
      const rows: DemoRecord[] = []
      for (const item of items) {
        const row = current.get(item.id)!
        const values: Partial<NewDemoRecord> = {}
        if (typeof item.board_order === 'number' && item.board_order !== row.board_order) values.board_order = item.board_order
        if (typeof item.sort_order === 'number' && item.sort_order !== row.sort_order) values.sort_order = item.sort_order
        if (item.status && item.status !== row.status) values.status = item.status
        if (item.parent_id !== undefined && item.parent_id !== row.parent_id) values.parent_id = item.parent_id
        if (Object.keys(values).length === 0) continue
        const updated = await repo.update(item.id, values)
        if (updated) rows.push(updated)
      }
      return rows
    })
    for (const row of changed) await this.events?.emit('demo_record.updated', demoRecordToDict(row))
    return { message: '排序成功', updated: changed.length }
  }

  /** Export: fields default to all export fields; empty ids exports everything; xlsx by default */
  async exportItems(options: z.output<typeof demoRecordExportBody>) {
    const fileType = normalizeTableFileType(options.file_type, 'xlsx')
    const fields = exportColumns(options.fields, EXPORT_FIELD_MAP)
    const ids = options.ids.length > 0 ? options.ids : null

    const items = await this.repo.listForExport(ids)
    const headers = fields.map((f) => fieldLabel(f))
    const rows = items.map((item) => {
      const dict: Record<string, unknown> = demoRecordToDict(item)
      return fields.map((f) => {
        const column = EXPORT_FIELD_MAP[f]
        if (Array.isArray(column)) return column[1](item)
        return f in dict ? dict[f] : ''
      })
    })
    return buildTable(headers, rows, 'demo_record_export', fileType)
  }

  async downloadTemplate(fileTypeRaw: unknown) {
    const fileType = normalizeTableFileType(fileTypeRaw, 'xlsx')
    return buildTable(Object.keys(IMPORT_HEADER_MAP), [], 'demo_record_import_template', fileType)
  }

  /**
   * Import: the whole batch is one transaction; any error row rolls it all back and returns 400 + error_rows.
   * A row's parent (the parent_id column, a record id) must already exist; dates must be in order.
   */
  async importItems(file: UploadedFile | null) {
    let table
    try {
      table = await readTableFile(file)
    } catch (err) {
      if (err instanceof TableFileError) throw new ServiceError(err.message, 400)
      throw err
    }
    const requiredHeader = Object.keys(IMPORT_HEADER_MAP)[0] ?? ''

    return this.inTx(async (repo) => {
      let created = 0
      const errors: ErrorRow[] = []
      for (const [line, row] of table.rows) {
        if (!(row[requiredHeader] ?? '').trim()) {
          errors.push(buildErrorRow(line, `${requiredHeader}不能为空`, row))
          continue
        }
        const mapped: Record<string, string> = {}
        for (const [header, value] of Object.entries(row)) {
          const field = IMPORT_HEADER_MAP[header]
          if (field && value) mapped[field] = value
        }
        let values
        try {
          values = parseBody(demoRecordBody, rowToBody(mapped))
          checkDates(values.start_date, values.end_date)
          await this.checkParent(repo, null, values.parent_id)
        } catch (err) {
          if (!(err instanceof ServiceError)) throw err
          errors.push(buildErrorRow(line, err.message, row))
          continue
        }
        try {
          await repo.insert(values)
        } catch (err) {
          // The database rejected this row (unique conflict, too long, ...): the transaction is aborted, so return it with the error rows found so far
          const rowError = dbConstraintError(err)
          if (!rowError) throw err
          errors.push(buildErrorRow(line, rowError.message, row))
          throw new ServiceError('导入失败，存在错误数据', 400, { error_rows: errors.slice(0, 500), error_count: errors.length })
        }
        created += 1
      }
      if (errors.length > 0) {
        // Throw so the whole transaction rolls back
        throw new ServiceError('导入失败，存在错误数据', 400, {
          error_rows: errors.slice(0, 500),
          error_count: errors.length,
        })
      }
      return { message: '导入成功', created, updated: 0 }
    })
  }
}
